In [1]:
import tensorflow as tf

In [2]:
def inference(X):
    #compute input X
    pass
def loss(X, Y):
    #compute loss
    pass
def inputs():
    #input data
    pass
def train(total_loss):
    #train total loss
    pass
def evaluate(loss, X, Y):
    #evaluate
    pass

In [4]:
with tf.Session() as sess:
    #tf.initialize_all_variables.run()
    
    #X, Y = inputs()
    #total_loss = loss(X, Y)
    #train_op = train(total_loss)
    #coord = tf.train.Coordinator()
    
    #threads = tf.train.start_queue_runners(sess=sess, coord=coord)
    
    #training_steps = 1000
    #for step in range(training_steps):
    #    sess.run([train_op])
    #    if step % 10 == 0:
    #        print 'loss: ', sess.run([total_loss])
    #    evaluate(sess, X, Y)
    
    #coord.request_stop()
    #coord.join(threads)
    pass

In [40]:
with tf.Session() as sess:
    feature_1 = tf.range(-5, 5)
    feature_2 = tf.to_float(tf.range(-3, 3))
    feature_3 = tf.constant([[-0.1,0.3],[0,1]])
    print feature_3
    print sess.run(tf.nn.relu(feature_1))
    print sess.run(tf.sigmoid(feature_2))
    print sess.run(tf.tanh(feature_2))
    print sess.run(tf.nn.dropout(feature_3, keep_prob=0.7))

Tensor("Const_21:0", shape=(2, 2), dtype=float32)
[0 0 0 0 0 0 1 2 3 4]
[ 0.04742587  0.11920292  0.26894143  0.5         0.7310586   0.88079703]
[-0.99505472 -0.96402758 -0.76159418  0.          0.76159418  0.96402758]
[[-0.14285715  0.42857146]
 [ 0.          1.42857146]]
